// Code generated by ent, DO NOT EDIT.

package teammember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldDeletedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldTeamID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldUserID, v))
}

// SubQuota applies equality check predicate on the "sub_quota" field. It's identical to SubQuotaEQ.
func SubQuota(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldSubQuota, v))
}

// SubQuotaUsed applies equality check predicate on the "sub_quota_used" field. It's identical to SubQuotaUsedEQ.
func SubQuotaUsed(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldSubQuotaUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotNull(FieldDeletedAt))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldTeamID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldUserID, vs...))
}

// SubQuotaEQ applies the EQ predicate on the "sub_quota" field.
func SubQuotaEQ(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldSubQuota, v))
}

// SubQuotaNEQ applies the NEQ predicate on the "sub_quota" field.
func SubQuotaNEQ(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldSubQuota, v))
}

// SubQuotaIn applies the In predicate on the "sub_quota" field.
func SubQuotaIn(vs ...float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldSubQuota, vs...))
}

// SubQuotaNotIn applies the NotIn predicate on the "sub_quota" field.
func SubQuotaNotIn(vs ...float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldSubQuota, vs...))
}

// SubQuotaGT applies the GT predicate on the "sub_quota" field.
func SubQuotaGT(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldSubQuota, v))
}

// SubQuotaGTE applies the GTE predicate on the "sub_quota" field.
func SubQuotaGTE(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldSubQuota, v))
}

// SubQuotaLT applies the LT predicate on the "sub_quota" field.
func SubQuotaLT(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldSubQuota, v))
}

// SubQuotaLTE applies the LTE predicate on the "sub_quota" field.
func SubQuotaLTE(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldSubQuota, v))
}

// SubQuotaUsedEQ applies the EQ predicate on the "sub_quota_used" field.
func SubQuotaUsedEQ(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldEQ(FieldSubQuotaUsed, v))
}

// SubQuotaUsedNEQ applies the NEQ predicate on the "sub_quota_used" field.
func SubQuotaUsedNEQ(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNEQ(FieldSubQuotaUsed, v))
}

// SubQuotaUsedIn applies the In predicate on the "sub_quota_used" field.
func SubQuotaUsedIn(vs ...float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIn(FieldSubQuotaUsed, vs...))
}

// SubQuotaUsedNotIn applies the NotIn predicate on the "sub_quota_used" field.
func SubQuotaUsedNotIn(vs ...float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotIn(FieldSubQuotaUsed, vs...))
}

// SubQuotaUsedGT applies the GT predicate on the "sub_quota_used" field.
func SubQuotaUsedGT(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGT(FieldSubQuotaUsed, v))
}

// SubQuotaUsedGTE applies the GTE predicate on the "sub_quota_used" field.
func SubQuotaUsedGTE(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldGTE(FieldSubQuotaUsed, v))
}

// SubQuotaUsedLT applies the LT predicate on the "sub_quota_used" field.
func SubQuotaUsedLT(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLT(FieldSubQuotaUsed, v))
}

// SubQuotaUsedLTE applies the LTE predicate on the "sub_quota_used" field.
func SubQuotaUsedLTE(v float64) predicate.TeamMember {
	return predicate.TeamMember(sql.FieldLTE(FieldSubQuotaUsed, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.TeamMember {
	return predicate.TeamMember(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.TeamMember {
	return predicate.TeamMember(sql.FieldNotNull(FieldTags))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamMember {
	return predicate.TeamMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamMember {
	return predicate.TeamMember(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TeamMember {
	return predicate.TeamMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TeamMember {
	return predicate.TeamMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamMember) predicate.TeamMember {
	return predicate.TeamMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamMember) predicate.TeamMember {
	return predicate.TeamMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamMember) predicate.TeamMember {
	return predicate.TeamMember(sql.NotPredicates(p))
}
