// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teambalancelog"
)

// TeamBalanceLog is the model entity for the TeamBalanceLog schema.
type TeamBalanceLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// recharge | subscription_purchase
	Type string `json:"type,omitempty"`
	// Positive = credit, negative = debit
	Amount float64 `json:"amount,omitempty"`
	// User who triggered the operation
	OperatorID int64 `json:"operator_id,omitempty"`
	// Recipient user for subscription_purchase
	TargetUserID *int64 `json:"target_user_id,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamBalanceLogQuery when eager-loading is set.
	Edges        TeamBalanceLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamBalanceLogEdges holds the relations/edges for other nodes in the graph.
type TeamBalanceLogEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamBalanceLogEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamBalanceLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teambalancelog.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case teambalancelog.FieldID, teambalancelog.FieldTeamID, teambalancelog.FieldOperatorID, teambalancelog.FieldTargetUserID:
			values[i] = new(sql.NullInt64)
		case teambalancelog.FieldType, teambalancelog.FieldNote:
			values[i] = new(sql.NullString)
		case teambalancelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamBalanceLog fields.
func (_m *TeamBalanceLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teambalancelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teambalancelog.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.Int64
			}
		case teambalancelog.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case teambalancelog.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case teambalancelog.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = value.Int64
			}
		case teambalancelog.FieldTargetUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value.Valid {
				_m.TargetUserID = new(int64)
				*_m.TargetUserID = value.Int64
			}
		case teambalancelog.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case teambalancelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamBalanceLog.
// This includes values selected through modifiers, order, etc.
func (_m *TeamBalanceLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamBalanceLog entity.
func (_m *TeamBalanceLog) QueryTeam() *TeamQuery {
	return NewTeamBalanceLogClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this TeamBalanceLog.
// Note that you need to call TeamBalanceLog.Unwrap() before calling this method if this TeamBalanceLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamBalanceLog) Update() *TeamBalanceLogUpdateOne {
	return NewTeamBalanceLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamBalanceLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamBalanceLog) Unwrap() *TeamBalanceLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamBalanceLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamBalanceLog) String() string {
	var builder strings.Builder
	builder.WriteString("TeamBalanceLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("operator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorID))
	builder.WriteString(", ")
	if v := _m.TargetUserID; v != nil {
		builder.WriteString("target_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamBalanceLogs is a parsable slice of TeamBalanceLog.
type TeamBalanceLogs []*TeamBalanceLog
