// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teambalancelog"
)

// TeamBalanceLogUpdate is the builder for updating TeamBalanceLog entities.
type TeamBalanceLogUpdate struct {
	config
	hooks    []Hook
	mutation *TeamBalanceLogMutation
}

// Where appends a list predicates to the TeamBalanceLogUpdate builder.
func (_u *TeamBalanceLogUpdate) Where(ps ...predicate.TeamBalanceLog) *TeamBalanceLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamBalanceLogUpdate) SetTeamID(v int64) *TeamBalanceLogUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableTeamID(v *int64) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeamBalanceLogUpdate) SetType(v string) *TeamBalanceLogUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableType(v *string) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TeamBalanceLogUpdate) SetAmount(v float64) *TeamBalanceLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableAmount(v *float64) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TeamBalanceLogUpdate) AddAmount(v float64) *TeamBalanceLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *TeamBalanceLogUpdate) SetOperatorID(v int64) *TeamBalanceLogUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableOperatorID(v *int64) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *TeamBalanceLogUpdate) AddOperatorID(v int64) *TeamBalanceLogUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *TeamBalanceLogUpdate) SetTargetUserID(v int64) *TeamBalanceLogUpdate {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableTargetUserID(v *int64) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *TeamBalanceLogUpdate) AddTargetUserID(v int64) *TeamBalanceLogUpdate {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *TeamBalanceLogUpdate) ClearTargetUserID() *TeamBalanceLogUpdate {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetNote sets the "note" field.
func (_u *TeamBalanceLogUpdate) SetNote(v string) *TeamBalanceLogUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TeamBalanceLogUpdate) SetNillableNote(v *string) *TeamBalanceLogUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *TeamBalanceLogUpdate) ClearNote() *TeamBalanceLogUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamBalanceLogUpdate) SetTeam(v *Team) *TeamBalanceLogUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamBalanceLogMutation object of the builder.
func (_u *TeamBalanceLogUpdate) Mutation() *TeamBalanceLogMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamBalanceLogUpdate) ClearTeam() *TeamBalanceLogUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamBalanceLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamBalanceLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamBalanceLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamBalanceLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamBalanceLogUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := teambalancelog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TeamBalanceLog.type": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamBalanceLog.team"`)
	}
	return nil
}

func (_u *TeamBalanceLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teambalancelog.Table, teambalancelog.Columns, sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(teambalancelog.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(teambalancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(teambalancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(teambalancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(teambalancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(teambalancelog.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(teambalancelog.FieldTargetUserID, field.TypeInt64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(teambalancelog.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(teambalancelog.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(teambalancelog.FieldNote, field.TypeString)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teambalancelog.TeamTable,
			Columns: []string{teambalancelog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teambalancelog.TeamTable,
			Columns: []string{teambalancelog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teambalancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamBalanceLogUpdateOne is the builder for updating a single TeamBalanceLog entity.
type TeamBalanceLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamBalanceLogMutation
}

// SetTeamID sets the "team_id" field.
func (_u *TeamBalanceLogUpdateOne) SetTeamID(v int64) *TeamBalanceLogUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableTeamID(v *int64) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeamBalanceLogUpdateOne) SetType(v string) *TeamBalanceLogUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableType(v *string) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TeamBalanceLogUpdateOne) SetAmount(v float64) *TeamBalanceLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableAmount(v *float64) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TeamBalanceLogUpdateOne) AddAmount(v float64) *TeamBalanceLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *TeamBalanceLogUpdateOne) SetOperatorID(v int64) *TeamBalanceLogUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableOperatorID(v *int64) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *TeamBalanceLogUpdateOne) AddOperatorID(v int64) *TeamBalanceLogUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *TeamBalanceLogUpdateOne) SetTargetUserID(v int64) *TeamBalanceLogUpdateOne {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableTargetUserID(v *int64) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *TeamBalanceLogUpdateOne) AddTargetUserID(v int64) *TeamBalanceLogUpdateOne {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *TeamBalanceLogUpdateOne) ClearTargetUserID() *TeamBalanceLogUpdateOne {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetNote sets the "note" field.
func (_u *TeamBalanceLogUpdateOne) SetNote(v string) *TeamBalanceLogUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TeamBalanceLogUpdateOne) SetNillableNote(v *string) *TeamBalanceLogUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *TeamBalanceLogUpdateOne) ClearNote() *TeamBalanceLogUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamBalanceLogUpdateOne) SetTeam(v *Team) *TeamBalanceLogUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamBalanceLogMutation object of the builder.
func (_u *TeamBalanceLogUpdateOne) Mutation() *TeamBalanceLogMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamBalanceLogUpdateOne) ClearTeam() *TeamBalanceLogUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamBalanceLogUpdate builder.
func (_u *TeamBalanceLogUpdateOne) Where(ps ...predicate.TeamBalanceLog) *TeamBalanceLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamBalanceLogUpdateOne) Select(field string, fields ...string) *TeamBalanceLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamBalanceLog entity.
func (_u *TeamBalanceLogUpdateOne) Save(ctx context.Context) (*TeamBalanceLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamBalanceLogUpdateOne) SaveX(ctx context.Context) *TeamBalanceLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamBalanceLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamBalanceLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamBalanceLogUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := teambalancelog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TeamBalanceLog.type": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamBalanceLog.team"`)
	}
	return nil
}

func (_u *TeamBalanceLogUpdateOne) sqlSave(ctx context.Context) (_node *TeamBalanceLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teambalancelog.Table, teambalancelog.Columns, sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamBalanceLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teambalancelog.FieldID)
		for _, f := range fields {
			if !teambalancelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teambalancelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(teambalancelog.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(teambalancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(teambalancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(teambalancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(teambalancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(teambalancelog.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(teambalancelog.FieldTargetUserID, field.TypeInt64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(teambalancelog.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(teambalancelog.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(teambalancelog.FieldNote, field.TypeString)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teambalancelog.TeamTable,
			Columns: []string{teambalancelog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teambalancelog.TeamTable,
			Columns: []string{teambalancelog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamBalanceLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teambalancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
