// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamadmin"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamAdminCreate is the builder for creating a TeamAdmin entity.
type TeamAdminCreate struct {
	config
	mutation *TeamAdminMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamAdminCreate) SetCreatedAt(v time.Time) *TeamAdminCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamAdminCreate) SetNillableCreatedAt(v *time.Time) *TeamAdminCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamAdminCreate) SetUpdatedAt(v time.Time) *TeamAdminCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamAdminCreate) SetNillableUpdatedAt(v *time.Time) *TeamAdminCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TeamAdminCreate) SetDeletedAt(v time.Time) *TeamAdminCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TeamAdminCreate) SetNillableDeletedAt(v *time.Time) *TeamAdminCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamAdminCreate) SetTeamID(v int64) *TeamAdminCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamAdminCreate) SetUserID(v int64) *TeamAdminCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamAdminCreate) SetTeam(v *Team) *TeamAdminCreate {
	return _c.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *TeamAdminCreate) SetUser(v *User) *TeamAdminCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TeamAdminMutation object of the builder.
func (_c *TeamAdminCreate) Mutation() *TeamAdminMutation {
	return _c.mutation
}

// Save creates the TeamAdmin in the database.
func (_c *TeamAdminCreate) Save(ctx context.Context) (*TeamAdmin, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamAdminCreate) SaveX(ctx context.Context) *TeamAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamAdminCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamAdminCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamAdminCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if teamadmin.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamadmin.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := teamadmin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if teamadmin.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamadmin.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamadmin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamAdminCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamAdmin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamAdmin.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamAdmin.team_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamAdmin.user_id"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamAdmin.team"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TeamAdmin.user"`)}
	}
	return nil
}

func (_c *TeamAdminCreate) sqlSave(ctx context.Context) (*TeamAdmin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamAdminCreate) createSpec() (*TeamAdmin, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamAdmin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamadmin.Table, sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamadmin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadmin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(teamadmin.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.TeamTable,
			Columns: []string{teamadmin.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.UserTable,
			Columns: []string{teamadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamAdmin.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamAdminUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamAdminCreate) OnConflict(opts ...sql.ConflictOption) *TeamAdminUpsertOne {
	_c.conflict = opts
	return &TeamAdminUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamAdminCreate) OnConflictColumns(columns ...string) *TeamAdminUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamAdminUpsertOne{
		create: _c,
	}
}

type (
	// TeamAdminUpsertOne is the builder for "upsert"-ing
	//  one TeamAdmin node.
	TeamAdminUpsertOne struct {
		create *TeamAdminCreate
	}

	// TeamAdminUpsert is the "OnConflict" setter.
	TeamAdminUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamAdminUpsert) SetUpdatedAt(v time.Time) *TeamAdminUpsert {
	u.Set(teamadmin.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamAdminUpsert) UpdateUpdatedAt() *TeamAdminUpsert {
	u.SetExcluded(teamadmin.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamAdminUpsert) SetDeletedAt(v time.Time) *TeamAdminUpsert {
	u.Set(teamadmin.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamAdminUpsert) UpdateDeletedAt() *TeamAdminUpsert {
	u.SetExcluded(teamadmin.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamAdminUpsert) ClearDeletedAt() *TeamAdminUpsert {
	u.SetNull(teamadmin.FieldDeletedAt)
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamAdminUpsert) SetTeamID(v int64) *TeamAdminUpsert {
	u.Set(teamadmin.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAdminUpsert) UpdateTeamID() *TeamAdminUpsert {
	u.SetExcluded(teamadmin.FieldTeamID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamAdminUpsert) SetUserID(v int64) *TeamAdminUpsert {
	u.Set(teamadmin.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAdminUpsert) UpdateUserID() *TeamAdminUpsert {
	u.SetExcluded(teamadmin.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamAdminUpsertOne) UpdateNewValues() *TeamAdminUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teamadmin.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamAdminUpsertOne) Ignore() *TeamAdminUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamAdminUpsertOne) DoNothing() *TeamAdminUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamAdminCreate.OnConflict
// documentation for more info.
func (u *TeamAdminUpsertOne) Update(set func(*TeamAdminUpsert)) *TeamAdminUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamAdminUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamAdminUpsertOne) SetUpdatedAt(v time.Time) *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamAdminUpsertOne) UpdateUpdatedAt() *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamAdminUpsertOne) SetDeletedAt(v time.Time) *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamAdminUpsertOne) UpdateDeletedAt() *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamAdminUpsertOne) ClearDeletedAt() *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamAdminUpsertOne) SetTeamID(v int64) *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAdminUpsertOne) UpdateTeamID() *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamAdminUpsertOne) SetUserID(v int64) *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAdminUpsertOne) UpdateUserID() *TeamAdminUpsertOne {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *TeamAdminUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamAdminCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamAdminUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamAdminUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamAdminUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamAdminCreateBulk is the builder for creating many TeamAdmin entities in bulk.
type TeamAdminCreateBulk struct {
	config
	err      error
	builders []*TeamAdminCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamAdmin entities in the database.
func (_c *TeamAdminCreateBulk) Save(ctx context.Context) ([]*TeamAdmin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamAdmin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamAdminMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamAdminCreateBulk) SaveX(ctx context.Context) []*TeamAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamAdminCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamAdminCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamAdmin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamAdminUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamAdminCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamAdminUpsertBulk {
	_c.conflict = opts
	return &TeamAdminUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamAdminCreateBulk) OnConflictColumns(columns ...string) *TeamAdminUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamAdminUpsertBulk{
		create: _c,
	}
}

// TeamAdminUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamAdmin nodes.
type TeamAdminUpsertBulk struct {
	create *TeamAdminCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamAdminUpsertBulk) UpdateNewValues() *TeamAdminUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teamadmin.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamAdmin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamAdminUpsertBulk) Ignore() *TeamAdminUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamAdminUpsertBulk) DoNothing() *TeamAdminUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamAdminCreateBulk.OnConflict
// documentation for more info.
func (u *TeamAdminUpsertBulk) Update(set func(*TeamAdminUpsert)) *TeamAdminUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamAdminUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamAdminUpsertBulk) SetUpdatedAt(v time.Time) *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamAdminUpsertBulk) UpdateUpdatedAt() *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamAdminUpsertBulk) SetDeletedAt(v time.Time) *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamAdminUpsertBulk) UpdateDeletedAt() *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamAdminUpsertBulk) ClearDeletedAt() *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamAdminUpsertBulk) SetTeamID(v int64) *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAdminUpsertBulk) UpdateTeamID() *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamAdminUpsertBulk) SetUserID(v int64) *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAdminUpsertBulk) UpdateUserID() *TeamAdminUpsertBulk {
	return u.Update(func(s *TeamAdminUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *TeamAdminUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamAdminCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamAdminCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamAdminUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
