// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamadmin"
	"github.com/Wei-Shaw/sub2api/ent/teambalancelog"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdate) SetUpdatedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamUpdate) SetDeletedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDeletedAt(v *time.Time) *TeamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamUpdate) ClearDeletedAt() *TeamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdate) SetName(v string) *TeamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableName(v *string) *TeamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *TeamUpdate) SetBalance(v float64) *TeamUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableBalance(v *float64) *TeamUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *TeamUpdate) AddBalance(v float64) *TeamUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetAvailableTags sets the "available_tags" field.
func (_u *TeamUpdate) SetAvailableTags(v []string) *TeamUpdate {
	_u.mutation.SetAvailableTags(v)
	return _u
}

// AppendAvailableTags appends value to the "available_tags" field.
func (_u *TeamUpdate) AppendAvailableTags(v []string) *TeamUpdate {
	_u.mutation.AppendAvailableTags(v)
	return _u
}

// ClearAvailableTags clears the value of the "available_tags" field.
func (_u *TeamUpdate) ClearAvailableTags() *TeamUpdate {
	_u.mutation.ClearAvailableTags()
	return _u
}

// SetMaxMembers sets the "max_members" field.
func (_u *TeamUpdate) SetMaxMembers(v int) *TeamUpdate {
	_u.mutation.ResetMaxMembers()
	_u.mutation.SetMaxMembers(v)
	return _u
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableMaxMembers(v *int) *TeamUpdate {
	if v != nil {
		_u.SetMaxMembers(*v)
	}
	return _u
}

// AddMaxMembers adds value to the "max_members" field.
func (_u *TeamUpdate) AddMaxMembers(v int) *TeamUpdate {
	_u.mutation.AddMaxMembers(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_u *TeamUpdate) AddMemberIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_u *TeamUpdate) AddMembers(v ...*TeamMember) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the TeamAdmin entity by IDs.
func (_u *TeamUpdate) AddAdminIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the TeamAdmin entity.
func (_u *TeamUpdate) AddAdmins(v ...*TeamAdmin) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddBalanceLogIDs adds the "balance_logs" edge to the TeamBalanceLog entity by IDs.
func (_u *TeamUpdate) AddBalanceLogIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddBalanceLogIDs(ids...)
	return _u
}

// AddBalanceLogs adds the "balance_logs" edges to the TeamBalanceLog entity.
func (_u *TeamUpdate) AddBalanceLogs(v ...*TeamBalanceLog) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBalanceLogIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *TeamUpdate) AddAPIKeyIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *TeamUpdate) AddAPIKeys(v ...*APIKey) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *TeamUpdate) AddSubscriptionIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *TeamUpdate) AddSubscriptions(v ...*UserSubscription) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (_u *TeamUpdate) ClearMembers() *TeamUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (_u *TeamUpdate) RemoveMemberIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (_u *TeamUpdate) RemoveMembers(v ...*TeamMember) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the TeamAdmin entity.
func (_u *TeamUpdate) ClearAdmins() *TeamUpdate {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to TeamAdmin entities by IDs.
func (_u *TeamUpdate) RemoveAdminIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to TeamAdmin entities.
func (_u *TeamUpdate) RemoveAdmins(v ...*TeamAdmin) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearBalanceLogs clears all "balance_logs" edges to the TeamBalanceLog entity.
func (_u *TeamUpdate) ClearBalanceLogs() *TeamUpdate {
	_u.mutation.ClearBalanceLogs()
	return _u
}

// RemoveBalanceLogIDs removes the "balance_logs" edge to TeamBalanceLog entities by IDs.
func (_u *TeamUpdate) RemoveBalanceLogIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveBalanceLogIDs(ids...)
	return _u
}

// RemoveBalanceLogs removes "balance_logs" edges to TeamBalanceLog entities.
func (_u *TeamUpdate) RemoveBalanceLogs(v ...*TeamBalanceLog) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBalanceLogIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *TeamUpdate) ClearAPIKeys() *TeamUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *TeamUpdate) RemoveAPIKeyIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *TeamUpdate) RemoveAPIKeys(v ...*APIKey) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *TeamUpdate) ClearSubscriptions() *TeamUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *TeamUpdate) RemoveSubscriptionIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *TeamUpdate) RemoveSubscriptions(v ...*UserSubscription) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if team.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(team.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(team.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(team.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableTags(); ok {
		_spec.SetField(team.FieldAvailableTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, team.FieldAvailableTags, value)
		})
	}
	if _u.mutation.AvailableTagsCleared() {
		_spec.ClearField(team.FieldAvailableTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxMembers(); ok {
		_spec.SetField(team.FieldMaxMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxMembers(); ok {
		_spec.AddField(team.FieldMaxMembers, field.TypeInt, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BalanceLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBalanceLogsIDs(); len(nodes) > 0 && !_u.mutation.BalanceLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BalanceLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdateOne) SetUpdatedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamUpdateOne) SetDeletedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDeletedAt(v *time.Time) *TeamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamUpdateOne) ClearDeletedAt() *TeamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdateOne) SetName(v string) *TeamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableName(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *TeamUpdateOne) SetBalance(v float64) *TeamUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableBalance(v *float64) *TeamUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *TeamUpdateOne) AddBalance(v float64) *TeamUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetAvailableTags sets the "available_tags" field.
func (_u *TeamUpdateOne) SetAvailableTags(v []string) *TeamUpdateOne {
	_u.mutation.SetAvailableTags(v)
	return _u
}

// AppendAvailableTags appends value to the "available_tags" field.
func (_u *TeamUpdateOne) AppendAvailableTags(v []string) *TeamUpdateOne {
	_u.mutation.AppendAvailableTags(v)
	return _u
}

// ClearAvailableTags clears the value of the "available_tags" field.
func (_u *TeamUpdateOne) ClearAvailableTags() *TeamUpdateOne {
	_u.mutation.ClearAvailableTags()
	return _u
}

// SetMaxMembers sets the "max_members" field.
func (_u *TeamUpdateOne) SetMaxMembers(v int) *TeamUpdateOne {
	_u.mutation.ResetMaxMembers()
	_u.mutation.SetMaxMembers(v)
	return _u
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableMaxMembers(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetMaxMembers(*v)
	}
	return _u
}

// AddMaxMembers adds value to the "max_members" field.
func (_u *TeamUpdateOne) AddMaxMembers(v int) *TeamUpdateOne {
	_u.mutation.AddMaxMembers(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_u *TeamUpdateOne) AddMemberIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_u *TeamUpdateOne) AddMembers(v ...*TeamMember) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the TeamAdmin entity by IDs.
func (_u *TeamUpdateOne) AddAdminIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the TeamAdmin entity.
func (_u *TeamUpdateOne) AddAdmins(v ...*TeamAdmin) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddBalanceLogIDs adds the "balance_logs" edge to the TeamBalanceLog entity by IDs.
func (_u *TeamUpdateOne) AddBalanceLogIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddBalanceLogIDs(ids...)
	return _u
}

// AddBalanceLogs adds the "balance_logs" edges to the TeamBalanceLog entity.
func (_u *TeamUpdateOne) AddBalanceLogs(v ...*TeamBalanceLog) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBalanceLogIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *TeamUpdateOne) AddAPIKeyIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *TeamUpdateOne) AddAPIKeys(v ...*APIKey) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *TeamUpdateOne) AddSubscriptionIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *TeamUpdateOne) AddSubscriptions(v ...*UserSubscription) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (_u *TeamUpdateOne) ClearMembers() *TeamUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (_u *TeamUpdateOne) RemoveMemberIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (_u *TeamUpdateOne) RemoveMembers(v ...*TeamMember) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the TeamAdmin entity.
func (_u *TeamUpdateOne) ClearAdmins() *TeamUpdateOne {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to TeamAdmin entities by IDs.
func (_u *TeamUpdateOne) RemoveAdminIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to TeamAdmin entities.
func (_u *TeamUpdateOne) RemoveAdmins(v ...*TeamAdmin) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearBalanceLogs clears all "balance_logs" edges to the TeamBalanceLog entity.
func (_u *TeamUpdateOne) ClearBalanceLogs() *TeamUpdateOne {
	_u.mutation.ClearBalanceLogs()
	return _u
}

// RemoveBalanceLogIDs removes the "balance_logs" edge to TeamBalanceLog entities by IDs.
func (_u *TeamUpdateOne) RemoveBalanceLogIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveBalanceLogIDs(ids...)
	return _u
}

// RemoveBalanceLogs removes "balance_logs" edges to TeamBalanceLog entities.
func (_u *TeamUpdateOne) RemoveBalanceLogs(v ...*TeamBalanceLog) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBalanceLogIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *TeamUpdateOne) ClearAPIKeys() *TeamUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *TeamUpdateOne) RemoveAPIKeyIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *TeamUpdateOne) RemoveAPIKeys(v ...*APIKey) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *TeamUpdateOne) ClearSubscriptions() *TeamUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *TeamUpdateOne) RemoveSubscriptionIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *TeamUpdateOne) RemoveSubscriptions(v ...*UserSubscription) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if team.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(team.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(team.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(team.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableTags(); ok {
		_spec.SetField(team.FieldAvailableTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, team.FieldAvailableTags, value)
		})
	}
	if _u.mutation.AvailableTagsCleared() {
		_spec.ClearField(team.FieldAvailableTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxMembers(); ok {
		_spec.SetField(team.FieldMaxMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxMembers(); ok {
		_spec.AddField(team.FieldMaxMembers, field.TypeInt, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BalanceLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBalanceLogsIDs(); len(nodes) > 0 && !_u.mutation.BalanceLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BalanceLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
