// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamadmin"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamAdminUpdate is the builder for updating TeamAdmin entities.
type TeamAdminUpdate struct {
	config
	hooks    []Hook
	mutation *TeamAdminMutation
}

// Where appends a list predicates to the TeamAdminUpdate builder.
func (_u *TeamAdminUpdate) Where(ps ...predicate.TeamAdmin) *TeamAdminUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamAdminUpdate) SetUpdatedAt(v time.Time) *TeamAdminUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamAdminUpdate) SetDeletedAt(v time.Time) *TeamAdminUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamAdminUpdate) SetNillableDeletedAt(v *time.Time) *TeamAdminUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamAdminUpdate) ClearDeletedAt() *TeamAdminUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamAdminUpdate) SetTeamID(v int64) *TeamAdminUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamAdminUpdate) SetNillableTeamID(v *int64) *TeamAdminUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamAdminUpdate) SetUserID(v int64) *TeamAdminUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamAdminUpdate) SetNillableUserID(v *int64) *TeamAdminUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamAdminUpdate) SetTeam(v *Team) *TeamAdminUpdate {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamAdminUpdate) SetUser(v *User) *TeamAdminUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamAdminMutation object of the builder.
func (_u *TeamAdminUpdate) Mutation() *TeamAdminMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamAdminUpdate) ClearTeam() *TeamAdminUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamAdminUpdate) ClearUser() *TeamAdminUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamAdminUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamAdminUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamAdminUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamAdminUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamAdminUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if teamadmin.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamadmin.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamadmin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamAdminUpdate) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAdmin.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAdmin.user"`)
	}
	return nil
}

func (_u *TeamAdminUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamadmin.Table, teamadmin.Columns, sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadmin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(teamadmin.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(teamadmin.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.TeamTable,
			Columns: []string{teamadmin.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.TeamTable,
			Columns: []string{teamadmin.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.UserTable,
			Columns: []string{teamadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.UserTable,
			Columns: []string{teamadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamAdminUpdateOne is the builder for updating a single TeamAdmin entity.
type TeamAdminUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamAdminMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamAdminUpdateOne) SetUpdatedAt(v time.Time) *TeamAdminUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamAdminUpdateOne) SetDeletedAt(v time.Time) *TeamAdminUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamAdminUpdateOne) SetNillableDeletedAt(v *time.Time) *TeamAdminUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamAdminUpdateOne) ClearDeletedAt() *TeamAdminUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamAdminUpdateOne) SetTeamID(v int64) *TeamAdminUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamAdminUpdateOne) SetNillableTeamID(v *int64) *TeamAdminUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamAdminUpdateOne) SetUserID(v int64) *TeamAdminUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamAdminUpdateOne) SetNillableUserID(v *int64) *TeamAdminUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamAdminUpdateOne) SetTeam(v *Team) *TeamAdminUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamAdminUpdateOne) SetUser(v *User) *TeamAdminUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamAdminMutation object of the builder.
func (_u *TeamAdminUpdateOne) Mutation() *TeamAdminMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamAdminUpdateOne) ClearTeam() *TeamAdminUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamAdminUpdateOne) ClearUser() *TeamAdminUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TeamAdminUpdate builder.
func (_u *TeamAdminUpdateOne) Where(ps ...predicate.TeamAdmin) *TeamAdminUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamAdminUpdateOne) Select(field string, fields ...string) *TeamAdminUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamAdmin entity.
func (_u *TeamAdminUpdateOne) Save(ctx context.Context) (*TeamAdmin, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamAdminUpdateOne) SaveX(ctx context.Context) *TeamAdmin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamAdminUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamAdminUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamAdminUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if teamadmin.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamadmin.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamadmin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamAdminUpdateOne) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAdmin.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAdmin.user"`)
	}
	return nil
}

func (_u *TeamAdminUpdateOne) sqlSave(ctx context.Context) (_node *TeamAdmin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamadmin.Table, teamadmin.Columns, sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamAdmin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamadmin.FieldID)
		for _, f := range fields {
			if !teamadmin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamadmin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadmin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(teamadmin.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(teamadmin.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.TeamTable,
			Columns: []string{teamadmin.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.TeamTable,
			Columns: []string{teamadmin.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.UserTable,
			Columns: []string{teamadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamadmin.UserTable,
			Columns: []string{teamadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamAdmin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
