// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamMemberCreate is the builder for creating a TeamMember entity.
type TeamMemberCreate struct {
	config
	mutation *TeamMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamMemberCreate) SetCreatedAt(v time.Time) *TeamMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableCreatedAt(v *time.Time) *TeamMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamMemberCreate) SetUpdatedAt(v time.Time) *TeamMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableUpdatedAt(v *time.Time) *TeamMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TeamMemberCreate) SetDeletedAt(v time.Time) *TeamMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableDeletedAt(v *time.Time) *TeamMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamMemberCreate) SetTeamID(v int64) *TeamMemberCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamMemberCreate) SetUserID(v int64) *TeamMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubQuota sets the "sub_quota" field.
func (_c *TeamMemberCreate) SetSubQuota(v float64) *TeamMemberCreate {
	_c.mutation.SetSubQuota(v)
	return _c
}

// SetNillableSubQuota sets the "sub_quota" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableSubQuota(v *float64) *TeamMemberCreate {
	if v != nil {
		_c.SetSubQuota(*v)
	}
	return _c
}

// SetSubQuotaUsed sets the "sub_quota_used" field.
func (_c *TeamMemberCreate) SetSubQuotaUsed(v float64) *TeamMemberCreate {
	_c.mutation.SetSubQuotaUsed(v)
	return _c
}

// SetNillableSubQuotaUsed sets the "sub_quota_used" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableSubQuotaUsed(v *float64) *TeamMemberCreate {
	if v != nil {
		_c.SetSubQuotaUsed(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *TeamMemberCreate) SetTags(v []string) *TeamMemberCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMemberCreate) SetTeam(v *Team) *TeamMemberCreate {
	return _c.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *TeamMemberCreate) SetUser(v *User) *TeamMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_c *TeamMemberCreate) Mutation() *TeamMemberMutation {
	return _c.mutation
}

// Save creates the TeamMember in the database.
func (_c *TeamMemberCreate) Save(ctx context.Context) (*TeamMember, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMemberCreate) SaveX(ctx context.Context) *TeamMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMemberCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if teammember.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized teammember.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := teammember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if teammember.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teammember.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teammember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SubQuota(); !ok {
		v := teammember.DefaultSubQuota
		_c.mutation.SetSubQuota(v)
	}
	if _, ok := _c.mutation.SubQuotaUsed(); !ok {
		v := teammember.DefaultSubQuotaUsed
		_c.mutation.SetSubQuotaUsed(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamMember.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamMember.team_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamMember.user_id"`)}
	}
	if _, ok := _c.mutation.SubQuota(); !ok {
		return &ValidationError{Name: "sub_quota", err: errors.New(`ent: missing required field "TeamMember.sub_quota"`)}
	}
	if _, ok := _c.mutation.SubQuotaUsed(); !ok {
		return &ValidationError{Name: "sub_quota_used", err: errors.New(`ent: missing required field "TeamMember.sub_quota_used"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamMember.team"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TeamMember.user"`)}
	}
	return nil
}

func (_c *TeamMemberCreate) sqlSave(ctx context.Context) (*TeamMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMemberCreate) createSpec() (*TeamMember, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammember.Table, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teammember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(teammember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.SubQuota(); ok {
		_spec.SetField(teammember.FieldSubQuota, field.TypeFloat64, value)
		_node.SubQuota = value
	}
	if value, ok := _c.mutation.SubQuotaUsed(); ok {
		_spec.SetField(teammember.FieldSubQuotaUsed, field.TypeFloat64, value)
		_node.SubQuotaUsed = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(teammember.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.TeamTable,
			Columns: []string{teammember.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.UserTable,
			Columns: []string{teammember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMemberCreate) OnConflict(opts ...sql.ConflictOption) *TeamMemberUpsertOne {
	_c.conflict = opts
	return &TeamMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMemberCreate) OnConflictColumns(columns ...string) *TeamMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMemberUpsertOne{
		create: _c,
	}
}

type (
	// TeamMemberUpsertOne is the builder for "upsert"-ing
	//  one TeamMember node.
	TeamMemberUpsertOne struct {
		create *TeamMemberCreate
	}

	// TeamMemberUpsert is the "OnConflict" setter.
	TeamMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsert) SetUpdatedAt(v time.Time) *TeamMemberUpsert {
	u.Set(teammember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateUpdatedAt() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamMemberUpsert) SetDeletedAt(v time.Time) *TeamMemberUpsert {
	u.Set(teammember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateDeletedAt() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamMemberUpsert) ClearDeletedAt() *TeamMemberUpsert {
	u.SetNull(teammember.FieldDeletedAt)
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamMemberUpsert) SetTeamID(v int64) *TeamMemberUpsert {
	u.Set(teammember.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateTeamID() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldTeamID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamMemberUpsert) SetUserID(v int64) *TeamMemberUpsert {
	u.Set(teammember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateUserID() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldUserID)
	return u
}

// SetSubQuota sets the "sub_quota" field.
func (u *TeamMemberUpsert) SetSubQuota(v float64) *TeamMemberUpsert {
	u.Set(teammember.FieldSubQuota, v)
	return u
}

// UpdateSubQuota sets the "sub_quota" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateSubQuota() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldSubQuota)
	return u
}

// AddSubQuota adds v to the "sub_quota" field.
func (u *TeamMemberUpsert) AddSubQuota(v float64) *TeamMemberUpsert {
	u.Add(teammember.FieldSubQuota, v)
	return u
}

// SetSubQuotaUsed sets the "sub_quota_used" field.
func (u *TeamMemberUpsert) SetSubQuotaUsed(v float64) *TeamMemberUpsert {
	u.Set(teammember.FieldSubQuotaUsed, v)
	return u
}

// UpdateSubQuotaUsed sets the "sub_quota_used" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateSubQuotaUsed() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldSubQuotaUsed)
	return u
}

// AddSubQuotaUsed adds v to the "sub_quota_used" field.
func (u *TeamMemberUpsert) AddSubQuotaUsed(v float64) *TeamMemberUpsert {
	u.Add(teammember.FieldSubQuotaUsed, v)
	return u
}

// SetTags sets the "tags" field.
func (u *TeamMemberUpsert) SetTags(v []string) *TeamMemberUpsert {
	u.Set(teammember.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateTags() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *TeamMemberUpsert) ClearTags() *TeamMemberUpsert {
	u.SetNull(teammember.FieldTags)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMemberUpsertOne) UpdateNewValues() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teammember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamMemberUpsertOne) Ignore() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMemberUpsertOne) DoNothing() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMemberCreate.OnConflict
// documentation for more info.
func (u *TeamMemberUpsertOne) Update(set func(*TeamMemberUpsert)) *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsertOne) SetUpdatedAt(v time.Time) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateUpdatedAt() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamMemberUpsertOne) SetDeletedAt(v time.Time) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateDeletedAt() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamMemberUpsertOne) ClearDeletedAt() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMemberUpsertOne) SetTeamID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateTeamID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMemberUpsertOne) SetUserID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateUserID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetSubQuota sets the "sub_quota" field.
func (u *TeamMemberUpsertOne) SetSubQuota(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetSubQuota(v)
	})
}

// AddSubQuota adds v to the "sub_quota" field.
func (u *TeamMemberUpsertOne) AddSubQuota(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddSubQuota(v)
	})
}

// UpdateSubQuota sets the "sub_quota" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateSubQuota() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateSubQuota()
	})
}

// SetSubQuotaUsed sets the "sub_quota_used" field.
func (u *TeamMemberUpsertOne) SetSubQuotaUsed(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetSubQuotaUsed(v)
	})
}

// AddSubQuotaUsed adds v to the "sub_quota_used" field.
func (u *TeamMemberUpsertOne) AddSubQuotaUsed(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddSubQuotaUsed(v)
	})
}

// UpdateSubQuotaUsed sets the "sub_quota_used" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateSubQuotaUsed() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateSubQuotaUsed()
	})
}

// SetTags sets the "tags" field.
func (u *TeamMemberUpsertOne) SetTags(v []string) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateTags() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *TeamMemberUpsertOne) ClearTags() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *TeamMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamMemberCreateBulk is the builder for creating many TeamMember entities in bulk.
type TeamMemberCreateBulk struct {
	config
	err      error
	builders []*TeamMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamMember entities in the database.
func (_c *TeamMemberCreateBulk) Save(ctx context.Context) ([]*TeamMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMemberCreateBulk) SaveX(ctx context.Context) []*TeamMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamMemberUpsertBulk {
	_c.conflict = opts
	return &TeamMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMemberCreateBulk) OnConflictColumns(columns ...string) *TeamMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMemberUpsertBulk{
		create: _c,
	}
}

// TeamMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamMember nodes.
type TeamMemberUpsertBulk struct {
	create *TeamMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMemberUpsertBulk) UpdateNewValues() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teammember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamMemberUpsertBulk) Ignore() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMemberUpsertBulk) DoNothing() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMemberCreateBulk.OnConflict
// documentation for more info.
func (u *TeamMemberUpsertBulk) Update(set func(*TeamMemberUpsert)) *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsertBulk) SetUpdatedAt(v time.Time) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateUpdatedAt() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamMemberUpsertBulk) SetDeletedAt(v time.Time) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateDeletedAt() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamMemberUpsertBulk) ClearDeletedAt() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMemberUpsertBulk) SetTeamID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateTeamID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMemberUpsertBulk) SetUserID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateUserID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetSubQuota sets the "sub_quota" field.
func (u *TeamMemberUpsertBulk) SetSubQuota(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetSubQuota(v)
	})
}

// AddSubQuota adds v to the "sub_quota" field.
func (u *TeamMemberUpsertBulk) AddSubQuota(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddSubQuota(v)
	})
}

// UpdateSubQuota sets the "sub_quota" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateSubQuota() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateSubQuota()
	})
}

// SetSubQuotaUsed sets the "sub_quota_used" field.
func (u *TeamMemberUpsertBulk) SetSubQuotaUsed(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetSubQuotaUsed(v)
	})
}

// AddSubQuotaUsed adds v to the "sub_quota_used" field.
func (u *TeamMemberUpsertBulk) AddSubQuotaUsed(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddSubQuotaUsed(v)
	})
}

// UpdateSubQuotaUsed sets the "sub_quota_used" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateSubQuotaUsed() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateSubQuotaUsed()
	})
}

// SetTags sets the "tags" field.
func (u *TeamMemberUpsertBulk) SetTags(v []string) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateTags() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *TeamMemberUpsertBulk) ClearTags() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *TeamMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
