// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teambalancelog"
)

// TeamBalanceLogCreate is the builder for creating a TeamBalanceLog entity.
type TeamBalanceLogCreate struct {
	config
	mutation *TeamBalanceLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTeamID sets the "team_id" field.
func (_c *TeamBalanceLogCreate) SetTeamID(v int64) *TeamBalanceLogCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TeamBalanceLogCreate) SetType(v string) *TeamBalanceLogCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TeamBalanceLogCreate) SetAmount(v float64) *TeamBalanceLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *TeamBalanceLogCreate) SetOperatorID(v int64) *TeamBalanceLogCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *TeamBalanceLogCreate) SetTargetUserID(v int64) *TeamBalanceLogCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_c *TeamBalanceLogCreate) SetNillableTargetUserID(v *int64) *TeamBalanceLogCreate {
	if v != nil {
		_c.SetTargetUserID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *TeamBalanceLogCreate) SetNote(v string) *TeamBalanceLogCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *TeamBalanceLogCreate) SetNillableNote(v *string) *TeamBalanceLogCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamBalanceLogCreate) SetCreatedAt(v time.Time) *TeamBalanceLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamBalanceLogCreate) SetNillableCreatedAt(v *time.Time) *TeamBalanceLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamBalanceLogCreate) SetTeam(v *Team) *TeamBalanceLogCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamBalanceLogMutation object of the builder.
func (_c *TeamBalanceLogCreate) Mutation() *TeamBalanceLogMutation {
	return _c.mutation
}

// Save creates the TeamBalanceLog in the database.
func (_c *TeamBalanceLogCreate) Save(ctx context.Context) (*TeamBalanceLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamBalanceLogCreate) SaveX(ctx context.Context) *TeamBalanceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamBalanceLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamBalanceLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamBalanceLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teambalancelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamBalanceLogCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamBalanceLog.team_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TeamBalanceLog.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := teambalancelog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TeamBalanceLog.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TeamBalanceLog.amount"`)}
	}
	if _, ok := _c.mutation.OperatorID(); !ok {
		return &ValidationError{Name: "operator_id", err: errors.New(`ent: missing required field "TeamBalanceLog.operator_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamBalanceLog.created_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamBalanceLog.team"`)}
	}
	return nil
}

func (_c *TeamBalanceLogCreate) sqlSave(ctx context.Context) (*TeamBalanceLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamBalanceLogCreate) createSpec() (*TeamBalanceLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamBalanceLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teambalancelog.Table, sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(teambalancelog.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(teambalancelog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(teambalancelog.FieldOperatorID, field.TypeInt64, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.TargetUserID(); ok {
		_spec.SetField(teambalancelog.FieldTargetUserID, field.TypeInt64, value)
		_node.TargetUserID = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(teambalancelog.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teambalancelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teambalancelog.TeamTable,
			Columns: []string{teambalancelog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamBalanceLog.Create().
//		SetTeamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamBalanceLogUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamBalanceLogCreate) OnConflict(opts ...sql.ConflictOption) *TeamBalanceLogUpsertOne {
	_c.conflict = opts
	return &TeamBalanceLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamBalanceLogCreate) OnConflictColumns(columns ...string) *TeamBalanceLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamBalanceLogUpsertOne{
		create: _c,
	}
}

type (
	// TeamBalanceLogUpsertOne is the builder for "upsert"-ing
	//  one TeamBalanceLog node.
	TeamBalanceLogUpsertOne struct {
		create *TeamBalanceLogCreate
	}

	// TeamBalanceLogUpsert is the "OnConflict" setter.
	TeamBalanceLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetTeamID sets the "team_id" field.
func (u *TeamBalanceLogUpsert) SetTeamID(v int64) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateTeamID() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldTeamID)
	return u
}

// SetType sets the "type" field.
func (u *TeamBalanceLogUpsert) SetType(v string) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateType() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldType)
	return u
}

// SetAmount sets the "amount" field.
func (u *TeamBalanceLogUpsert) SetAmount(v float64) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateAmount() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TeamBalanceLogUpsert) AddAmount(v float64) *TeamBalanceLogUpsert {
	u.Add(teambalancelog.FieldAmount, v)
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamBalanceLogUpsert) SetOperatorID(v int64) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateOperatorID() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldOperatorID)
	return u
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamBalanceLogUpsert) AddOperatorID(v int64) *TeamBalanceLogUpsert {
	u.Add(teambalancelog.FieldOperatorID, v)
	return u
}

// SetTargetUserID sets the "target_user_id" field.
func (u *TeamBalanceLogUpsert) SetTargetUserID(v int64) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldTargetUserID, v)
	return u
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateTargetUserID() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldTargetUserID)
	return u
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *TeamBalanceLogUpsert) AddTargetUserID(v int64) *TeamBalanceLogUpsert {
	u.Add(teambalancelog.FieldTargetUserID, v)
	return u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *TeamBalanceLogUpsert) ClearTargetUserID() *TeamBalanceLogUpsert {
	u.SetNull(teambalancelog.FieldTargetUserID)
	return u
}

// SetNote sets the "note" field.
func (u *TeamBalanceLogUpsert) SetNote(v string) *TeamBalanceLogUpsert {
	u.Set(teambalancelog.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamBalanceLogUpsert) UpdateNote() *TeamBalanceLogUpsert {
	u.SetExcluded(teambalancelog.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *TeamBalanceLogUpsert) ClearNote() *TeamBalanceLogUpsert {
	u.SetNull(teambalancelog.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamBalanceLogUpsertOne) UpdateNewValues() *TeamBalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teambalancelog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamBalanceLogUpsertOne) Ignore() *TeamBalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamBalanceLogUpsertOne) DoNothing() *TeamBalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamBalanceLogCreate.OnConflict
// documentation for more info.
func (u *TeamBalanceLogUpsertOne) Update(set func(*TeamBalanceLogUpsert)) *TeamBalanceLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamBalanceLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamBalanceLogUpsertOne) SetTeamID(v int64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateTeamID() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateTeamID()
	})
}

// SetType sets the "type" field.
func (u *TeamBalanceLogUpsertOne) SetType(v string) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateType() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateType()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamBalanceLogUpsertOne) SetAmount(v float64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamBalanceLogUpsertOne) AddAmount(v float64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateAmount() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateAmount()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamBalanceLogUpsertOne) SetOperatorID(v int64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamBalanceLogUpsertOne) AddOperatorID(v int64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateOperatorID() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateOperatorID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *TeamBalanceLogUpsertOne) SetTargetUserID(v int64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *TeamBalanceLogUpsertOne) AddTargetUserID(v int64) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateTargetUserID() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *TeamBalanceLogUpsertOne) ClearTargetUserID() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.ClearTargetUserID()
	})
}

// SetNote sets the "note" field.
func (u *TeamBalanceLogUpsertOne) SetNote(v string) *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertOne) UpdateNote() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *TeamBalanceLogUpsertOne) ClearNote() *TeamBalanceLogUpsertOne {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *TeamBalanceLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamBalanceLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamBalanceLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamBalanceLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamBalanceLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamBalanceLogCreateBulk is the builder for creating many TeamBalanceLog entities in bulk.
type TeamBalanceLogCreateBulk struct {
	config
	err      error
	builders []*TeamBalanceLogCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamBalanceLog entities in the database.
func (_c *TeamBalanceLogCreateBulk) Save(ctx context.Context) ([]*TeamBalanceLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamBalanceLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamBalanceLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamBalanceLogCreateBulk) SaveX(ctx context.Context) []*TeamBalanceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamBalanceLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamBalanceLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamBalanceLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamBalanceLogUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamBalanceLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamBalanceLogUpsertBulk {
	_c.conflict = opts
	return &TeamBalanceLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamBalanceLogCreateBulk) OnConflictColumns(columns ...string) *TeamBalanceLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamBalanceLogUpsertBulk{
		create: _c,
	}
}

// TeamBalanceLogUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamBalanceLog nodes.
type TeamBalanceLogUpsertBulk struct {
	create *TeamBalanceLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamBalanceLogUpsertBulk) UpdateNewValues() *TeamBalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teambalancelog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamBalanceLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamBalanceLogUpsertBulk) Ignore() *TeamBalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamBalanceLogUpsertBulk) DoNothing() *TeamBalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamBalanceLogCreateBulk.OnConflict
// documentation for more info.
func (u *TeamBalanceLogUpsertBulk) Update(set func(*TeamBalanceLogUpsert)) *TeamBalanceLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamBalanceLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamBalanceLogUpsertBulk) SetTeamID(v int64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateTeamID() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateTeamID()
	})
}

// SetType sets the "type" field.
func (u *TeamBalanceLogUpsertBulk) SetType(v string) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateType() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateType()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamBalanceLogUpsertBulk) SetAmount(v float64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamBalanceLogUpsertBulk) AddAmount(v float64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateAmount() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateAmount()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamBalanceLogUpsertBulk) SetOperatorID(v int64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamBalanceLogUpsertBulk) AddOperatorID(v int64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateOperatorID() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateOperatorID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *TeamBalanceLogUpsertBulk) SetTargetUserID(v int64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *TeamBalanceLogUpsertBulk) AddTargetUserID(v int64) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateTargetUserID() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *TeamBalanceLogUpsertBulk) ClearTargetUserID() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.ClearTargetUserID()
	})
}

// SetNote sets the "note" field.
func (u *TeamBalanceLogUpsertBulk) SetNote(v string) *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamBalanceLogUpsertBulk) UpdateNote() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *TeamBalanceLogUpsertBulk) ClearNote() *TeamBalanceLogUpsertBulk {
	return u.Update(func(s *TeamBalanceLogUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *TeamBalanceLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamBalanceLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamBalanceLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamBalanceLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
