// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/team"
)

// Team is the model entity for the Team schema.
type Team struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Team balance in USD
	Balance float64 `json:"balance,omitempty"`
	// Team-defined tag set used for member tagging
	AvailableTags []string `json:"available_tags,omitempty"`
	// Cap on active paying members (0 = unlimited). Only sys admin can modify.
	MaxMembers int `json:"max_members,omitempty"`
	// When false, team_admin cannot see the Subscriptions tab nor call subscription endpoints. Sys admin always can.
	SubscriptionsEnabled bool `json:"subscriptions_enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamQuery when eager-loading is set.
	Edges        TeamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamEdges holds the relations/edges for other nodes in the graph.
type TeamEdges struct {
	// Members holds the value of the members edge.
	Members []*TeamMember `json:"members,omitempty"`
	// Admins holds the value of the admins edge.
	Admins []*TeamAdmin `json:"admins,omitempty"`
	// BalanceLogs holds the value of the balance_logs edge.
	BalanceLogs []*TeamBalanceLog `json:"balance_logs,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) MembersOrErr() ([]*TeamMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// AdminsOrErr returns the Admins value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) AdminsOrErr() ([]*TeamAdmin, error) {
	if e.loadedTypes[1] {
		return e.Admins, nil
	}
	return nil, &NotLoadedError{edge: "admins"}
}

// BalanceLogsOrErr returns the BalanceLogs value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) BalanceLogsOrErr() ([]*TeamBalanceLog, error) {
	if e.loadedTypes[2] {
		return e.BalanceLogs, nil
	}
	return nil, &NotLoadedError{edge: "balance_logs"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[3] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e TeamEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[4] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Team) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case team.FieldAvailableTags:
			values[i] = new([]byte)
		case team.FieldSubscriptionsEnabled:
			values[i] = new(sql.NullBool)
		case team.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case team.FieldID, team.FieldMaxMembers:
			values[i] = new(sql.NullInt64)
		case team.FieldName:
			values[i] = new(sql.NullString)
		case team.FieldCreatedAt, team.FieldUpdatedAt, team.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Team fields.
func (_m *Team) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case team.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case team.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case team.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case team.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case team.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case team.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case team.FieldAvailableTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field available_tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AvailableTags); err != nil {
					return fmt.Errorf("unmarshal field available_tags: %w", err)
				}
			}
		case team.FieldMaxMembers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_members", values[i])
			} else if value.Valid {
				_m.MaxMembers = int(value.Int64)
			}
		case team.FieldSubscriptionsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field subscriptions_enabled", values[i])
			} else if value.Valid {
				_m.SubscriptionsEnabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Team.
// This includes values selected through modifiers, order, etc.
func (_m *Team) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the Team entity.
func (_m *Team) QueryMembers() *TeamMemberQuery {
	return NewTeamClient(_m.config).QueryMembers(_m)
}

// QueryAdmins queries the "admins" edge of the Team entity.
func (_m *Team) QueryAdmins() *TeamAdminQuery {
	return NewTeamClient(_m.config).QueryAdmins(_m)
}

// QueryBalanceLogs queries the "balance_logs" edge of the Team entity.
func (_m *Team) QueryBalanceLogs() *TeamBalanceLogQuery {
	return NewTeamClient(_m.config).QueryBalanceLogs(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the Team entity.
func (_m *Team) QueryAPIKeys() *APIKeyQuery {
	return NewTeamClient(_m.config).QueryAPIKeys(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the Team entity.
func (_m *Team) QuerySubscriptions() *UserSubscriptionQuery {
	return NewTeamClient(_m.config).QuerySubscriptions(_m)
}

// Update returns a builder for updating this Team.
// Note that you need to call Team.Unwrap() before calling this method if this Team
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Team) Update() *TeamUpdateOne {
	return NewTeamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Team entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Team) Unwrap() *Team {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Team is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Team) String() string {
	var builder strings.Builder
	builder.WriteString("Team(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("available_tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableTags))
	builder.WriteString(", ")
	builder.WriteString("max_members=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxMembers))
	builder.WriteString(", ")
	builder.WriteString("subscriptions_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionsEnabled))
	builder.WriteByte(')')
	return builder.String()
}

// Teams is a parsable slice of Team.
type Teams []*Team
