// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamadmin"
	"github.com/Wei-Shaw/sub2api/ent/teambalancelog"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// TeamCreate is the builder for creating a Team entity.
type TeamCreate struct {
	config
	mutation *TeamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamCreate) SetCreatedAt(v time.Time) *TeamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableCreatedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamCreate) SetUpdatedAt(v time.Time) *TeamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableUpdatedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TeamCreate) SetDeletedAt(v time.Time) *TeamCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableDeletedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TeamCreate) SetName(v string) *TeamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *TeamCreate) SetBalance(v float64) *TeamCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *TeamCreate) SetNillableBalance(v *float64) *TeamCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetAvailableTags sets the "available_tags" field.
func (_c *TeamCreate) SetAvailableTags(v []string) *TeamCreate {
	_c.mutation.SetAvailableTags(v)
	return _c
}

// SetMaxMembers sets the "max_members" field.
func (_c *TeamCreate) SetMaxMembers(v int) *TeamCreate {
	_c.mutation.SetMaxMembers(v)
	return _c
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_c *TeamCreate) SetNillableMaxMembers(v *int) *TeamCreate {
	if v != nil {
		_c.SetMaxMembers(*v)
	}
	return _c
}

// SetSubscriptionsEnabled sets the "subscriptions_enabled" field.
func (_c *TeamCreate) SetSubscriptionsEnabled(v bool) *TeamCreate {
	_c.mutation.SetSubscriptionsEnabled(v)
	return _c
}

// SetNillableSubscriptionsEnabled sets the "subscriptions_enabled" field if the given value is not nil.
func (_c *TeamCreate) SetNillableSubscriptionsEnabled(v *bool) *TeamCreate {
	if v != nil {
		_c.SetSubscriptionsEnabled(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_c *TeamCreate) AddMemberIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_c *TeamCreate) AddMembers(v ...*TeamMember) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the TeamAdmin entity by IDs.
func (_c *TeamCreate) AddAdminIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddAdminIDs(ids...)
	return _c
}

// AddAdmins adds the "admins" edges to the TeamAdmin entity.
func (_c *TeamCreate) AddAdmins(v ...*TeamAdmin) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAdminIDs(ids...)
}

// AddBalanceLogIDs adds the "balance_logs" edge to the TeamBalanceLog entity by IDs.
func (_c *TeamCreate) AddBalanceLogIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddBalanceLogIDs(ids...)
	return _c
}

// AddBalanceLogs adds the "balance_logs" edges to the TeamBalanceLog entity.
func (_c *TeamCreate) AddBalanceLogs(v ...*TeamBalanceLog) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBalanceLogIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *TeamCreate) AddAPIKeyIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *TeamCreate) AddAPIKeys(v ...*APIKey) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_c *TeamCreate) AddSubscriptionIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_c *TeamCreate) AddSubscriptions(v ...*UserSubscription) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_c *TeamCreate) Mutation() *TeamMutation {
	return _c.mutation
}

// Save creates the Team in the database.
func (_c *TeamCreate) Save(ctx context.Context) (*Team, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamCreate) SaveX(ctx context.Context) *Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if team.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := team.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if team.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := team.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		v := team.DefaultMaxMembers
		_c.mutation.SetMaxMembers(v)
	}
	if _, ok := _c.mutation.SubscriptionsEnabled(); !ok {
		v := team.DefaultSubscriptionsEnabled
		_c.mutation.SetSubscriptionsEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Team.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Team.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Team.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Team.balance"`)}
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		return &ValidationError{Name: "max_members", err: errors.New(`ent: missing required field "Team.max_members"`)}
	}
	if _, ok := _c.mutation.SubscriptionsEnabled(); !ok {
		return &ValidationError{Name: "subscriptions_enabled", err: errors.New(`ent: missing required field "Team.subscriptions_enabled"`)}
	}
	return nil
}

func (_c *TeamCreate) sqlSave(ctx context.Context) (*Team, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamCreate) createSpec() (*Team, *sqlgraph.CreateSpec) {
	var (
		_node = &Team{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(team.Table, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(team.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(team.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.AvailableTags(); ok {
		_spec.SetField(team.FieldAvailableTags, field.TypeJSON, value)
		_node.AvailableTags = value
	}
	if value, ok := _c.mutation.MaxMembers(); ok {
		_spec.SetField(team.FieldMaxMembers, field.TypeInt, value)
		_node.MaxMembers = value
	}
	if value, ok := _c.mutation.SubscriptionsEnabled(); ok {
		_spec.SetField(team.FieldSubscriptionsEnabled, field.TypeBool, value)
		_node.SubscriptionsEnabled = value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.AdminsTable,
			Columns: []string{team.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamadmin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BalanceLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.BalanceLogsTable,
			Columns: []string{team.BalanceLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teambalancelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.SubscriptionsTable,
			Columns: []string{team.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamCreate) OnConflict(opts ...sql.ConflictOption) *TeamUpsertOne {
	_c.conflict = opts
	return &TeamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamCreate) OnConflictColumns(columns ...string) *TeamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertOne{
		create: _c,
	}
}

type (
	// TeamUpsertOne is the builder for "upsert"-ing
	//  one Team node.
	TeamUpsertOne struct {
		create *TeamCreate
	}

	// TeamUpsert is the "OnConflict" setter.
	TeamUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsert) SetUpdatedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateUpdatedAt() *TeamUpsert {
	u.SetExcluded(team.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsert) SetDeletedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateDeletedAt() *TeamUpsert {
	u.SetExcluded(team.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsert) ClearDeletedAt() *TeamUpsert {
	u.SetNull(team.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *TeamUpsert) SetName(v string) *TeamUpsert {
	u.Set(team.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsert) UpdateName() *TeamUpsert {
	u.SetExcluded(team.FieldName)
	return u
}

// SetBalance sets the "balance" field.
func (u *TeamUpsert) SetBalance(v float64) *TeamUpsert {
	u.Set(team.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TeamUpsert) UpdateBalance() *TeamUpsert {
	u.SetExcluded(team.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *TeamUpsert) AddBalance(v float64) *TeamUpsert {
	u.Add(team.FieldBalance, v)
	return u
}

// SetAvailableTags sets the "available_tags" field.
func (u *TeamUpsert) SetAvailableTags(v []string) *TeamUpsert {
	u.Set(team.FieldAvailableTags, v)
	return u
}

// UpdateAvailableTags sets the "available_tags" field to the value that was provided on create.
func (u *TeamUpsert) UpdateAvailableTags() *TeamUpsert {
	u.SetExcluded(team.FieldAvailableTags)
	return u
}

// ClearAvailableTags clears the value of the "available_tags" field.
func (u *TeamUpsert) ClearAvailableTags() *TeamUpsert {
	u.SetNull(team.FieldAvailableTags)
	return u
}

// SetMaxMembers sets the "max_members" field.
func (u *TeamUpsert) SetMaxMembers(v int) *TeamUpsert {
	u.Set(team.FieldMaxMembers, v)
	return u
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *TeamUpsert) UpdateMaxMembers() *TeamUpsert {
	u.SetExcluded(team.FieldMaxMembers)
	return u
}

// AddMaxMembers adds v to the "max_members" field.
func (u *TeamUpsert) AddMaxMembers(v int) *TeamUpsert {
	u.Add(team.FieldMaxMembers, v)
	return u
}

// SetSubscriptionsEnabled sets the "subscriptions_enabled" field.
func (u *TeamUpsert) SetSubscriptionsEnabled(v bool) *TeamUpsert {
	u.Set(team.FieldSubscriptionsEnabled, v)
	return u
}

// UpdateSubscriptionsEnabled sets the "subscriptions_enabled" field to the value that was provided on create.
func (u *TeamUpsert) UpdateSubscriptionsEnabled() *TeamUpsert {
	u.SetExcluded(team.FieldSubscriptionsEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertOne) UpdateNewValues() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(team.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamUpsertOne) Ignore() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertOne) DoNothing() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreate.OnConflict
// documentation for more info.
func (u *TeamUpsertOne) Update(set func(*TeamUpsert)) *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsertOne) SetUpdatedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateUpdatedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsertOne) SetDeletedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateDeletedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsertOne) ClearDeletedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *TeamUpsertOne) SetName(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateName() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetBalance sets the "balance" field.
func (u *TeamUpsertOne) SetBalance(v float64) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *TeamUpsertOne) AddBalance(v float64) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateBalance() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateBalance()
	})
}

// SetAvailableTags sets the "available_tags" field.
func (u *TeamUpsertOne) SetAvailableTags(v []string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetAvailableTags(v)
	})
}

// UpdateAvailableTags sets the "available_tags" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateAvailableTags() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateAvailableTags()
	})
}

// ClearAvailableTags clears the value of the "available_tags" field.
func (u *TeamUpsertOne) ClearAvailableTags() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearAvailableTags()
	})
}

// SetMaxMembers sets the "max_members" field.
func (u *TeamUpsertOne) SetMaxMembers(v int) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetMaxMembers(v)
	})
}

// AddMaxMembers adds v to the "max_members" field.
func (u *TeamUpsertOne) AddMaxMembers(v int) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.AddMaxMembers(v)
	})
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateMaxMembers() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateMaxMembers()
	})
}

// SetSubscriptionsEnabled sets the "subscriptions_enabled" field.
func (u *TeamUpsertOne) SetSubscriptionsEnabled(v bool) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetSubscriptionsEnabled(v)
	})
}

// UpdateSubscriptionsEnabled sets the "subscriptions_enabled" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateSubscriptionsEnabled() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateSubscriptionsEnabled()
	})
}

// Exec executes the query.
func (u *TeamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamCreateBulk is the builder for creating many Team entities in bulk.
type TeamCreateBulk struct {
	config
	err      error
	builders []*TeamCreate
	conflict []sql.ConflictOption
}

// Save creates the Team entities in the database.
func (_c *TeamCreateBulk) Save(ctx context.Context) ([]*Team, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Team, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamCreateBulk) SaveX(ctx context.Context) []*Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamUpsertBulk {
	_c.conflict = opts
	return &TeamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamCreateBulk) OnConflictColumns(columns ...string) *TeamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertBulk{
		create: _c,
	}
}

// TeamUpsertBulk is the builder for "upsert"-ing
// a bulk of Team nodes.
type TeamUpsertBulk struct {
	create *TeamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertBulk) UpdateNewValues() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(team.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamUpsertBulk) Ignore() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertBulk) DoNothing() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreateBulk.OnConflict
// documentation for more info.
func (u *TeamUpsertBulk) Update(set func(*TeamUpsert)) *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsertBulk) SetUpdatedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateUpdatedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsertBulk) SetDeletedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateDeletedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsertBulk) ClearDeletedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *TeamUpsertBulk) SetName(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateName() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetBalance sets the "balance" field.
func (u *TeamUpsertBulk) SetBalance(v float64) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *TeamUpsertBulk) AddBalance(v float64) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateBalance() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateBalance()
	})
}

// SetAvailableTags sets the "available_tags" field.
func (u *TeamUpsertBulk) SetAvailableTags(v []string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetAvailableTags(v)
	})
}

// UpdateAvailableTags sets the "available_tags" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateAvailableTags() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateAvailableTags()
	})
}

// ClearAvailableTags clears the value of the "available_tags" field.
func (u *TeamUpsertBulk) ClearAvailableTags() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearAvailableTags()
	})
}

// SetMaxMembers sets the "max_members" field.
func (u *TeamUpsertBulk) SetMaxMembers(v int) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetMaxMembers(v)
	})
}

// AddMaxMembers adds v to the "max_members" field.
func (u *TeamUpsertBulk) AddMaxMembers(v int) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.AddMaxMembers(v)
	})
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateMaxMembers() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateMaxMembers()
	})
}

// SetSubscriptionsEnabled sets the "subscriptions_enabled" field.
func (u *TeamUpsertBulk) SetSubscriptionsEnabled(v bool) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetSubscriptionsEnabled(v)
	})
}

// UpdateSubscriptionsEnabled sets the "subscriptions_enabled" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateSubscriptionsEnabled() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateSubscriptionsEnabled()
	})
}

// Exec executes the query.
func (u *TeamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
