// Code generated by ent, DO NOT EDIT.

package teambalancelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldID, id))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldTeamID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldAmount, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldOperatorID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldTargetUserID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldTeamID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldContainsFold(FieldType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldAmount, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldOperatorID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v int64) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDIsNil applies the IsNil predicate on the "target_user_id" field.
func TargetUserIDIsNil() predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIsNull(FieldTargetUserID))
}

// TargetUserIDNotNil applies the NotNil predicate on the "target_user_id" field.
func TargetUserIDNotNil() predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotNull(FieldTargetUserID))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamBalanceLog) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamBalanceLog) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamBalanceLog) predicate.TeamBalanceLog {
	return predicate.TeamBalanceLog(sql.NotPredicates(p))
}
